### ISSUE TITLE
Error fetching victorsmartkill data

### ISSUE THREAD

**Issue by mroffbeat** [toreamun/victorsmartkill-homeassistant#1]
clean install HACS / VictorsmartKill gives me the following error.
Promt for username/password seems to be oke.

Log Details (ERROR)

Logger: custom_components.victorsmartkill
Source: helpers/update_coordinator.py:165 
Integration: Victor Smart-Kill (documentation, issues) 
First occurred: 2:55:35 PM (3 occurrences) 
Last logged: 2:55:54 PM

Error fetching victorsmartkill data: {0: {'location': ['Field may not be null.'], 'long': ['Field may not be null.'], 'lat': ['Field may not be null.'], 'floor_plan_x': ['Field may not be null.'], 'floor_plan_y': ['Field may not be null.']}}

-->

## Version of the custom_component
"victor-smart-kill==0.0.5"

## Describe the bug
After adding the custom component the user/pass prompt comes up. This seems to be oke. 
The sensors are not activated. When checking the LOG, the error above shows up.

**Comment by toreamun** [comment]
Should be fixed in release 0.0.13.
Thanks for reporting the issue.

**Comment by mroffbeat** [comment]
wow, thanks so much.. just came home from Sweden and installed this trap which I bought at clas Olson .. everything works now. My house will flash RED when mouse is killed 👍
