### ISSUE TITLE
Unavailable after upgrading Home Assistant to 2022.7

### ISSUE THREAD

**Issue by mnewm4** [toreamun/victorsmartkill-homeassistant#27]
after updating Home Assistant, integration shows as unavailable.   I have deleted and readded the integration.

Firmware: 2.0.17
Hardware: WERT 

Logger: homeassistant.components.sensor
Source: helpers/update_coordinator.py:331
Integration: Sensor (documentation, issues)
First occurred: 10:44:46 AM (2 occurrences)
Last logged: 10:44:47 AM

Error adding entities for domain sensor with platform victorsmartkill
Error while setting up victorsmartkill platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/victorsmartkill/entity.py", line 124, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 331, in async_added_to_hass
    self.coordinator.async_add_listener(
TypeError: VictorSmartKillDataUpdateCoordinator.async_add_listener() takes 2 positional arguments but 3 were given

Logger: homeassistant.components.binary_sensor
Source: helpers/update_coordinator.py:331
Integration: Binary sensor (documentation, issues)
First occurred: 10:44:46 AM (2 occurrences)
Last logged: 10:44:47 AM

Error adding entities for domain binary_sensor with platform victorsmartkill
Error while setting up victorsmartkill platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/victorsmartkill/entity.py", line 124, in async_added_to_hass
    await super().async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 331, in async_added_to_hass
    self.coordinator.async_add_listener(
TypeError: VictorSmartKillDataUpdateCoordinator.async_add_listener() takes 2 positional arguments but 3 were given

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.7.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Chicago",
    "os_name": "Linux",
    "os_version": "5.15.32-v8",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.2",
    "docker_version": "20.10.14",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "victorsmartkill": {
      "version": "2022.2.3",
      "requirements": [
        "victor-smart-kill==1.1.0"
      ]
    },
    "localtuya": {
      "version": "4.0.1",
      "requirements": []
    },
    "scheduler": {
      "version": "v0.0.0",
      "requirements": []
    },
    "watchman": {
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "netdaemon": {
      "version": "22.05.0",
      "requirements": [
        "awesomeversion>=21.1.0"
      ]
    },
    "thermal_comfort": {
      "version": "1.4.3",
      "requirements": []
    },
    "weatheralerts": {
      "version": "0.1.5",
      "requirements": []
    },
    "garbage_collection": {
      "version": "4.7.8",
      "requirements": [
        "python-dateutil>=2.8.2"
      ]
    },
    "weatherapi": {
      "version": "0.8",
      "requirements": []
    },
    "iphonedetect": {
      "version": "1.4.0",
      "requirements": []
    },
    "openweathermaphistory": {
      "version": "1.0.5",
      "requirements": []
    },
    "tuya_local": {
      "version": "0.17.1",
      "requirements": [
        "pycryptodome~=3.14.1",
        "tinytuya~=1.6.0"
      ]
    },
    "mass": {
      "version": "2022.7.0b1",
      "requirements": [
        "music-assistant==1.6.0"
      ]
    },
    "hacs": {
      "version": "1.25.5",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "nodered": {
      "version": "1.0.8",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "victorsmartkill",
    "name": "Victor Smart-Kill",
    "version": "2022.2.3",
    "documentation": "https://github.com/toreamun/victorsmartkill-homeassistant",
    "issue_tracker": "https://github.com/toreamun/victorsmartkill-homeassistant/issues",
    "dependencies": [],
    "config_flow": true,
    "codeowners": [
      "@toreamun"
    ],
    "requirements": [
      "victor-smart-kill==1.1.0"
    ],
    "iot_class": "cloud_polling",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "860bfbf0b48ceae36f4b23128f34a24c",
      "version": 1,
      "domain": "victorsmartkill",
      "title": "**REDACTED**",
      "data": {
        "username": "**REDACTED**",
        "password": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "**REDACTED**",
      "disabled_by": null
    },
    "data": {
      "146708": {
        "id": 146708,
        "url": "https://www.victorsmartkill.com/traps/146708/",
        "corruption_status": 0,
        "corruption_status_options": null,
        "operator": null,
        "operator_name": null,
        "name": "Garage1",
        "ssid": "**REDACTED**",
        "serial_number": "**REDACTED**",
        "auto_upgrade": false,
        "status": 0,
        "location": "https://www.victorsmartkill.com/locations/108067/",
        "lat": "**REDACTED**",
        "long": "**REDACTED**",
        "upgrade_firmware": null,
        "commercial_gateway": null,
        "commercial_monitor_mode_enabled": false,
        "lorawan_app_key": "**REDACTED**",
        "site_name": null,
        "floor_plan_x": 0,
        "floor_plan_y": 0,
        "building_name": null,
        "floor_name": null,
        "room": null,
        "room_name": null,
        "trap_type": 1,
        "trap_type_verbose": "Rat Trap",
        "alerts": 256561,
        "trapstatistics": {
          "id": 146708,
          "url": "https://www.victorsmartkill.com/trapstatistics/146708/",
          "trap": "https://www.victorsmartkill.com/traps/146708/",
          "trap_name": "Garage1",
          "kills_present": 0,
          "install_date": "2022-03-24T16:12:59.198428+00:00",
          "owner_name": "**REDACTED**",
          "owner_email": "**REDACTED**",
          "last_report_date": "2022-07-08T14:37:32.876301+00:00",
          "last_kill_date": "2022-04-30T11:17:53.842342+00:00",
          "temperature": 0,
          "battery_level": 31,
          "total_kills": 3,
          "total_escapes": 2,
          "rx_power_level": -60,
          "firmware_version": "2.0.17",
          "trap_provisioned": true,
          "last_sequence_number": null,
          "total_retreats": null,
          "wireless_network_rssi": -60,
          "error_code": 0,
          "send_conn_lost_nt": true,
          "send_empty_trap_nt": true,
          "board_type": "WERT",
          "last_maintenance_date": "No maintenance records exist."
        }
      }
    },
    "last_exception": null
  }
}

**Comment by Filialen** [comment]
Same here...

**Comment by FortranFour** [comment]
I also have the same issue.

**Comment by toreamun** [comment]
https://github.com/toreamun/victorsmartkill-homeassistant/releases/tag/2022.7.0

**Comment by FortranFour** [comment]
Awesome, thanks for fixing it so quickly!
