### ISSUE TITLE
can't add integration

### ISSUE THREAD

**Issue by solvan230** [toreamun/victorsmartkill-homeassistant#29]
Log showing this when setting up this integration.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/victorsmartkill/__init__.py", line 63, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, coordinator.platforms)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

**Comment by toreamun** [comment]
I was a bit fast to implement a new HA 2022.8 feature. Please roll back to previous release: [2022.7.0](https://github.com/toreamun/victorsmartkill-homeassistant/releases/tag/2022.7.0)

Sorry for the trouble. Thanks for reporting.

**Comment by solvan230** [comment]
No sorry needed. Downgraded and work as intended now.
Awesome works! Thank you so much 🙏🏻🙏🏻🤩
