### ISSUE TITLE
Integration will not display on 2021.1.3 with HACs 1.10

### ISSUE THREAD

**Issue by jonpaterson** [toreamun/victorsmartkill-homeassistant#3]
## Version of the custom_component

0.32
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
HACS 1.10 running on 2021.1.3.  Installs the custom component correctly but even after restart the integration is not available in the UI list. Other integrations via HACS have successfully installed.

## Debug log

```text

Add your logs here.

```

**Comment by toreamun** [comment]
This sounds a bit like issue #2 .

It sounds like it can be a home assistant integration list cache issue. I know that HACS documentations says that "Before HACS can show up in the list you need to clear your browser cache". Maybe this is sometime is the case with integrations installed using HACS as well.
