### ISSUE TITLE
Integrations stopped working

### ISSUE THREAD

**Issue by AseKarlsson** [toreamun/victorsmartkill-homeassistant#36]
Hi,

Just saw that my integration with HA stopped working:
![image](https://user-images.githubusercontent.com/80900477/214346506-4ca85841-76ef-4e27-bde4-d55503cd1030.png)
I dont know with what version of HA this happened, now on latest 2023.1.7
Anyone else with the same issue?
Also thought I would check for the login credentials for the Integration, but cant find where to look for it, please advice?

Thanks,
AseKarlsson

**Comment by dvhub** [comment]
I have the same issue.  It started Jan 23rd at 7:14 AM EST.  The error I'm seeing is:

This error originated from a custom integration.

Logger: custom_components.victorsmartkill
Source: helpers/update_coordinator.py:201
Integration: Victor Smart-Kill (documentation, issues)
First occurred: January 23, 2023 at 10:10:30 AM (1126 occurrences)
Last logged: 11:46:30 AM

Error fetching victorsmartkill data:
Error fetching victorsmartkill data: {0: {'trapstatistics': {'current_bait': ['Unknown field.'], 'last_bait_quantity': ['Unknown field.'], 'bait_level': ['Unknown field.']}}, 1: {'trapstatistics': {'current_bait': ['Unknown field.'], 'last_bait_quantity': ['Unknown field.'], 'bait_level': ['Unknown field.']}}, 2: {'trapstatistics': {'current_bait': ['Unknown field.'], 'last_bait_quantity': ['Unknown field.'], 'bait_level': ['Unknown field.']}}, 3: {'trapstatistics': {'current_bait': ['Unknown field.'], 'last_bait_quantity': ['Unknown field.'], 'bait_level': ['Unknown field.']}}, 4: {'trapstatistics': {'current_bait': ['Unknown field.'], 'last_bait_quantity': ['Unknown field.'], 'bait_level': ['Unknown field.']}}}

The Victor app is still working fine.

**Comment by dvhub** [comment]
> Hi,
> 
> Just saw that my integration with HA stopped working: ![image](https://user-images.githubusercontent.com/80900477/214346506-4ca85841-76ef-4e27-bde4-d55503cd1030.png) I dont know with what version of HA this happened, now on latest 2023.1.7 Anyone else with the same issue? Also thought I would check for the login credentials for the Integration, but cant find where to look for it, please advice?
> 
> Thanks, AseKarlsson

To update credentials, I believe you need to remove and re-add the integration.

**Comment by AseKarlsson** [comment]
> > Hi,
> > Just saw that my integration with HA stopped working: ![image](https://user-images.githubusercontent.com/80900477/214346506-4ca85841-76ef-4e27-bde4-d55503cd1030.png) I dont know with what version of HA this happened, now on latest 2023.1.7 Anyone else with the same issue? Also thought I would check for the login credentials for the Integration, but cant find where to look for it, please advice?
> > Thanks, AseKarlsson
> 
> To update credentials, I believe you need to remove and re-add the integration.

Tried to install the Integration on an other unit, but did not get any questions about credentials, maybe related to the same issue.

**Comment by Athep** [comment]
I got 'unavailable' status yesterday. The Victor App is still working here to.

**Comment by chummingMoney** [comment]
Following - I also have this issue.

**Comment by FortranFour** [comment]
Same here. Ironically right after a customer paid a visit.

**Comment by cbp0616** [comment]
Following. Just downloaded this integration for first time and same error originally posted

**Comment by trentjw** [comment]
Yuppers stopped working same error as screen shot above

**Comment by AseKarlsson** [comment]
@toreamun  , Can you please look at this issue?

Thanks,
AseKarlsson

**Comment by toreamun** [comment]
Looks like the API has been changed. I will look at it.

**Comment by AseKarlsson** [comment]
> Looks like the API has been changed. I will look at it.

Any good news on the progress?

**Comment by toreamun** [comment]
I have been busy, but I'm looking at it now.

**Comment by toreamun** [comment]
Should now be fixed by latest release https://github.com/toreamun/victorsmartkill-homeassistant/releases/tag/2023.1.0

**Comment by AseKarlsson** [comment]
Thanks Tore,
Will test, any info for non programmers what they changed?

**Comment by toreamun** [comment]
They added new fields. The plan was that the integration should just ignore unknown new fields, but this was not the case when fields are added to sub-structures... The setting to ignore unknown (in this case new) fields is not propagated to sub structures.

**Comment by AseKarlsson** [comment]
Thanks Tore for the clarification!
Was there any usable new fieds to add for the future of the integration?

**Comment by toreamun** [comment]
New trap fields are: last_bait_quantity, current_bait, bait_level
Probably for more advanced traps. 
I think I have to see the data to know how to use them. It is not clear exactly what data they will contain. Probably integers, but could also be codes.

**Comment by FortranFour** [comment]
Thanks immensely for writing this integration and for keeping it up to date.

The latest version seems to become unavailable often. It sometimes then becomes available again or else I just restart Home Assistant and it is connected again for a while.

**Comment by JonLaliberte** [comment]
@toreamun I've noticed the same - unavailable happening often.
