### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'victorsmartkill'

### ISSUE THREAD

**Issue by mroffbeat** [toreamun/victorsmartkill-homeassistant#4]
Logger: homeassistant.loader
Source: loader.py:802 
First occurred: 13:34:45 (1 occurrences) 
Last logged: 13:34:45

No 'version' key in the manifest file for custom integration 'victorsmartkill'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'victorsmartkill'

**Comment by toreamun** [comment]
Fixed :-)
Thanks.
