### ISSUE TITLE
Trap Battery level has a Lat/Long location assigned.

### ISSUE THREAD

**Issue by thayerfox** [toreamun/victorsmartkill-homeassistant#5]
I've noticed that my trap battery level sensor has a latitude/longitude assigned to it.  It is not accurate to where the trap is (off by about 30KM). 

Where is this information pulled from?  Is there any way to update/disable it, as it shows on the Map tab.

HASS config:
Victor smartkill integration 2021.3.0
Home Assistant 2021.3.4

**Comment by toreamun** [comment]
This information comes from the Victor Smart Kill API trap information and is associated with the trap. I think they store the location when the trap is installed/wifi-configured in the app. Is your inaccurate location a location your phone may have used as your location when you installed the trap?

I don't know if it is possible to disable attributes in Home Assistant user interface.

**Comment by thayerfox** [comment]
I wonder if they are grabbing the geolocation reported for whatever external IP the trap reports to Victor from.  The coordinates for mine point to the center of downtown for the main city nearby, no where close to where the trap was commissioned.

Could you perhaps have a config toggle in the integration to report trap lat/long, and then not populate the sensor lat/long if disabled?

**Comment by DTTerastar** [comment]
The Maps page shows the latt/long of the battery which is kinda wierd.

**Comment by toreamun** [comment]
My map does not show my battery. I don't know why. It could be nice to show low batteries on a map if you have devices spread around. But it is not a nice feature if the location is very "off" like reported. Maybe the feature should be removed or configurable like suggested earlier.
